pull_request_rules:
  - name: Automatic merge of scala-steward PR
    conditions:
      - author=scala-steward
      - check-success=CI / test (8, 1.2.8) (pull_request)
      - check-success=CI / test (8) (pull_request)
      - check-success=CI / test (11) (pull_request)
    actions:
      merge:
        method: merge
        strict: true
